spring:
  application:
    name: spring-keycloak

  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:9090/realms/dev/protocol/openid-connect/token/introspect
          client-id: c_dev
          client-secret: pydqjX0JXDTTcCOZ3rNcGoWVpFTNUFIk

server:
  port: 9873
